version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10-browsers
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install Git LFS
          command: |
            set +e
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get update
            sudo apt-get install -y git-lfs openssh-client
            git lfs install
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
            git lfs pull
      - node/install:
          install-yarn: true
          node-version: 14.2.0
      - run: npm install
      # - run: npm run test -- --coverage
      - run: npm run loki:ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
