version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    machine: true
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.2.0
      - run: npm install
      # - run: npm run test -- --coverage
      - run: npm run loki:ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
