import { isString, isNullOrUndefined } from 'utils/type-guards';

export const COLOR = [
  'white',
  'black',
  'grey',
  'rose',
  'red',
  'orange',
  'yellow',
  'lime',
  'green',
  'seafoam',
  'teal',
  'azure',
  'blue',
  'violet',
  'magenta',
] as const;
export type TColor = typeof COLOR[number];

export const SHADE = ['1', '2', '3', '4', '5', '6', '7', '8', '9'] as const;
export type TShade = typeof SHADE[number];

export const COLOR_SHADE = [
  'white',
  'black',
  'grey-1',
  'grey-2',
  'grey-3',
  'grey-4',
  'grey-5',
  'grey-6',
  'grey-7',
  'grey-8',
  'grey-9',
  'rose-1',
  'rose-2',
  'rose-3',
  'rose-4',
  'rose-5',
  'rose-6',
  'rose-7',
  'rose-8',
  'rose-9',
  'red-1',
  'red-2',
  'red-3',
  'red-4',
  'red-5',
  'red-6',
  'red-7',
  'red-8',
  'red-9',
  'orange-1',
  'orange-2',
  'orange-3',
  'orange-4',
  'orange-5',
  'orange-6',
  'orange-7',
  'orange-8',
  'orange-9',
  'yellow-1',
  'yellow-2',
  'yellow-3',
  'yellow-4',
  'yellow-5',
  'yellow-6',
  'yellow-7',
  'yellow-8',
  'yellow-9',
  'lime-1',
  'lime-2',
  'lime-3',
  'lime-4',
  'lime-5',
  'lime-6',
  'lime-7',
  'lime-8',
  'lime-9',
  'green-1',
  'green-2',
  'green-3',
  'green-4',
  'green-5',
  'green-6',
  'green-7',
  'green-8',
  'green-9',
  'seafoam-1',
  'seafoam-2',
  'seafoam-3',
  'seafoam-4',
  'seafoam-5',
  'seafoam-6',
  'seafoam-7',
  'seafoam-8',
  'seafoam-9',
  'teal-1',
  'teal-2',
  'teal-3',
  'teal-4',
  'teal-5',
  'teal-6',
  'teal-7',
  'teal-8',
  'teal-9',
  'azure-1',
  'azure-2',
  'azure-3',
  'azure-4',
  'azure-5',
  'azure-6',
  'azure-7',
  'azure-8',
  'azure-9',
  'blue-1',
  'blue-2',
  'blue-3',
  'blue-4',
  'blue-5',
  'blue-6',
  'blue-7',
  'blue-8',
  'blue-9',
  'violet-1',
  'violet-2',
  'violet-3',
  'violet-4',
  'violet-5',
  'violet-6',
  'violet-7',
  'violet-8',
  'violet-9',
  'magenta-1',
  'magenta-2',
  'magenta-3',
  'magenta-4',
  'magenta-5',
  'magenta-6',
  'magenta-7',
  'magenta-8',
  'magenta-9',
] as const;
export type TColorShade = typeof COLOR_SHADE[number];
export type TColorShadeProp = {
  [P in TColorShade]?: boolean;
};

export const BACKGROUND_COLOR = [
  'bg-transparent',
  'bg-white',
  'bg-black',
  'bg-grey-1',
  'bg-grey-2',
  'bg-grey-3',
  'bg-grey-4',
  'bg-grey-5',
  'bg-grey-6',
  'bg-grey-7',
  'bg-grey-8',
  'bg-grey-9',
  'bg-rose-1',
  'bg-rose-2',
  'bg-rose-3',
  'bg-rose-4',
  'bg-rose-5',
  'bg-rose-6',
  'bg-rose-7',
  'bg-rose-8',
  'bg-rose-9',
  'bg-red-1',
  'bg-red-2',
  'bg-red-3',
  'bg-red-4',
  'bg-red-5',
  'bg-red-6',
  'bg-red-7',
  'bg-red-8',
  'bg-red-9',
  'bg-orange-1',
  'bg-orange-2',
  'bg-orange-3',
  'bg-orange-4',
  'bg-orange-5',
  'bg-orange-6',
  'bg-orange-7',
  'bg-orange-8',
  'bg-orange-9',
  'bg-yellow-1',
  'bg-yellow-2',
  'bg-yellow-3',
  'bg-yellow-4',
  'bg-yellow-5',
  'bg-yellow-6',
  'bg-yellow-7',
  'bg-yellow-8',
  'bg-yellow-9',
  'bg-lime-1',
  'bg-lime-2',
  'bg-lime-3',
  'bg-lime-4',
  'bg-lime-5',
  'bg-lime-6',
  'bg-lime-7',
  'bg-lime-8',
  'bg-lime-9',
  'bg-green-1',
  'bg-green-2',
  'bg-green-3',
  'bg-green-4',
  'bg-green-5',
  'bg-green-6',
  'bg-green-7',
  'bg-green-8',
  'bg-green-9',
  'bg-seafoam-1',
  'bg-seafoam-2',
  'bg-seafoam-3',
  'bg-seafoam-4',
  'bg-seafoam-5',
  'bg-seafoam-6',
  'bg-seafoam-7',
  'bg-seafoam-8',
  'bg-seafoam-9',
  'bg-teal-1',
  'bg-teal-2',
  'bg-teal-3',
  'bg-teal-4',
  'bg-teal-5',
  'bg-teal-6',
  'bg-teal-7',
  'bg-teal-8',
  'bg-teal-9',
  'bg-azure-1',
  'bg-azure-2',
  'bg-azure-3',
  'bg-azure-4',
  'bg-azure-5',
  'bg-azure-6',
  'bg-azure-7',
  'bg-azure-8',
  'bg-azure-9',
  'bg-blue-1',
  'bg-blue-2',
  'bg-blue-3',
  'bg-blue-4',
  'bg-blue-5',
  'bg-blue-6',
  'bg-blue-7',
  'bg-blue-8',
  'bg-blue-9',
  'bg-violet-1',
  'bg-violet-2',
  'bg-violet-3',
  'bg-violet-4',
  'bg-violet-5',
  'bg-violet-6',
  'bg-violet-7',
  'bg-violet-8',
  'bg-violet-9',
  'bg-magenta-1',
  'bg-magenta-2',
  'bg-magenta-3',
  'bg-magenta-4',
  'bg-magenta-5',
  'bg-magenta-6',
  'bg-magenta-7',
  'bg-magenta-8',
  'bg-magenta-9',
] as const;
export type TBgColor = typeof BACKGROUND_COLOR[number];
export type TBgColorProp = {
  [P in TBgColor]?: boolean;
};

export interface IColorObject {
  color: TColor;
  shade?: TShade;
}

export const isColor = (value: any): value is TColor => COLOR.includes(value);
export const isShade = (value: any): value is TShade => SHADE.includes(value);
export const isColorObject = (value: any): value is IColorObject => {
  if (!isNullOrUndefined(value)) {
    const keys = Object.keys(value);
    // Only checking `color` because `shade` is not required
    return keys.includes('color');
  }
  return false;
};

export const colorIsInPalette = (value: any): boolean => {
  if (isString(value)) {
    const color = value.split('-')[0];
    return isColor(color);
  }
  return false;
};

export const getPaletteColor = (obj?: IColorObject) => {
  if (isColorObject(obj)) {
    const { color, shade = '5' } = obj;
    const isWhiteOrBlack = ['white', 'black'].includes(color);
    const colorString = isWhiteOrBlack ? color : `${color}-${shade}`;
    return colorIsInPalette(colorString) ? colorString : '';
  }
  return '';
};
